# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-15 08:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20171013_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 15, 8, 59, 36, 979151, tzinfo=utc)),
        ),
    ]
