# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-04 08:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20171102_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 4, 8, 16, 13, 615346, tzinfo=utc)),
        ),
    ]
