# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-18 09:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20171118_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 18, 9, 45, 56, 642028, tzinfo=utc)),
        ),
    ]
