# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-25 18:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20180125_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 25, 18, 49, 13, 793083, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='url',
            field=models.URLField(default='http://127.0.0.1:8000/post/kolejny-nowy-post'),
        ),
    ]
