# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-31 17:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20180129_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 31, 17, 59, 12, 417203, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='url',
            field=models.URLField(),
        ),
    ]
