# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-01 19:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20180201_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 1, 19, 12, 9, 143011, tzinfo=utc)),
        ),
    ]
